## More on `torch.Tensor` and `torch.tensor`

In [1]:
import torch


In [2]:
def pretty_print(obj, title=None):
    if title is not None:
        print(title)
    print(obj)
    print("\n")


In [3]:
# Type-autocasted tensors are exactly the same

xTens = torch.Tensor([[1.2, 3.8], [1, 32]])
xtens = torch.tensor([[1.2, 3.8], [1, 32]])

pretty_print(
    (xTens.dtype, xtens.dtype),
    "Types of Tensor and tensor containing compatible but different types.\nAutocasting to lowest-precision type (float32):",
)
pretty_print(
    (torch.linalg.norm(xtens), torch.linalg.norm(xTens)),
    "Norms are computed as expected:",
)


Types of Tensor and tensor containing compatible but different types.
Autocasting to lowest-precision type (float32):
(torch.float32, torch.float32)


Norms are computed as expected:
(tensor(32.2627), tensor(32.2627))




In [4]:
# Same-type tensors (but not Tensors) are type-inferred

xTens = torch.Tensor([[1, 3], [1, 32]])
xtens = torch.tensor([[1, 3], [1, 32]])

pretty_print(
    (xTens.dtype, xtens.dtype),
    "Types of Tensor and tensor containing integers.\nTensors cast to float32, tensors type-infer:",
)
pretty_print(torch.linalg.norm(xTens), "Norms of Tensors are computed as expected:")
print("But beware of tensor types!")
torch.linalg.norm(xtens)


Types of Tensor and tensor containing integers.
Tensors cast to float32, tensors type-infer:
(torch.float32, torch.int64)


Norms of Tensors are computed as expected:
tensor(32.1714)


But beware of tensor types!


RuntimeError: Can only calculate the norm of floating point and complex dtypes. Got Long instead.

In [5]:
# Explicitly type-casting torch tensors
# "Explicit is better than implicit" (The Zen of Python)

xtens = torch.tensor([[1, 3], [1, 32]], dtype=torch.float32)


In [6]:
# Constructing tensors from scalars and adimensional tensors

data = 3

datatensor = torch.tensor(data)
dataTensor = torch.Tensor(data)
dataTensorList = torch.Tensor([data])

pretty_print((dataTensor, dataTensor.shape), "Tensor(_): a random tensor of size 3")
pretty_print(
    (datatensor, datatensor.shape, datatensor.numel()),
    "tensor(_): an adimensional tensor (scalar) containing given scalar",
)
pretty_print(
    (dataTensorList, dataTensorList.shape, dataTensorList.numel()),
    "Tensor([_]): a 1-dimensional tensor of size 1 containing given scalar (type-casted to float32)",
)


Tensor(_): a random tensor of size 3
(tensor([8.5323e+22, 4.5857e-41, 1.1107e+23]), torch.Size([3]))


tensor(_): an adimensional tensor (scalar) containing given scalar
(tensor(3), torch.Size([]), 1)


Tensor([_]): a 1-dimensional tensor of size 1 containing given scalar (type-casted to float32)
(tensor([3.]), torch.Size([1]), 1)




In [7]:
# Empty tensors

emptyTensor = torch.Tensor()
pretty_print((emptyTensor, emptyTensor.shape), "Tensor(): empty Tensor")


Tensor(): empty Tensor
(tensor([]), torch.Size([0]))




In [8]:
emptytensor = torch.tensor()  # TypeError: missing "data" to build the tensor from


TypeError: tensor() missing 1 required positional arguments: "data"

In [9]:
emptytensor = torch.tensor(())
pretty_print(
    (emptytensor, emptytensor.shape),
    'tensor(()): empty Tensor ("data" is an empty list: "[]")',
)


tensor(()): empty Tensor ("data" is an empty list: "[]")
(tensor([]), torch.Size([0]))




In [10]:
randomtensor = torch.empty(100)

pretty_print(
    randomtensor,
    "Actually a random tensor of given size.\ntensor.empty(_) is the same as Tensor(_)",
)


Actually a random tensor of given size.
tensor.empty(_) is the same as Tensor(_)
tensor([       nan,        nan, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 1.2612e-44, 0.0000e+00, 1.0523e-22, 4.5856e-41,
        3.8695e+21, 3.0691e-41,        nan,        nan, 0.0000e+00, 0.0000e+00,
               nan,        nan, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00,
        1.0089e-43, 0.0000e+00, 1.5414e-44, 0.0000e+00, 1.0523e-22, 4.5856e-41,
        3.8695e+21, 3.0691e-41, 1.6816e-44, 0.0000e+00, 3.9236e-44, 0.0000e+00,
               nan,        nan, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00,
        2.0179e-43, 0.0000e+00, 1.5414e-44, 0.0000e+00, 1.0523e-22, 4.5856e-41,
        3.8695e+21, 3.0691e-41, 0.0000e+00, 0.0000e+00, 3.9236e-44, 0.0000e+00,
               nan,        nan, 1.4013e-44, 0.0000e+00, 1.4013e-45, 4.5856e-41,
        3.0268e-43, 0.0000e+00, 1.1210e-44, 0.0000e+00, 1.0523e-22, 4.5856e-41,
        3.8704e+21, 3.0691e-41, 5.4651e